---
layout: post
title: 18년 1월 11일 수업 내용 정리
description: 패스트캠퍼스 프론트엔드 스쿨 수업 내용 정리 (js) # Add post description (optional)
img: post-til.jpg # Add image post (optional)
tags: [패스트캠퍼스, til, js, javascript]
author: # Add name author (optional)
category: til
---
# 4 Day

## 1. 예외 처리

1. JavaScript에는 코드 실행 중에 예기치 못한 에러가 발생했을 때, 이로부터 코드의 실행 흐름을 복구할 수 있는 기능이 내장되어 있다. 이런 기능을 일러 **예외 처리(exception handling)**라고 한다.

<br />

### 1.1 동기식 코드에서의 예외 처리

1. JavaScript 코드에서 발생할 수 있는 에러에는 다양한 것들이 있다. 문법 에러와 같이 프로그래머의 실수로 인해 에러가 발생하는 경우도 있지만, 네트워크 에러와 같이 코드와는 무관한 이유로 발생하는 에러도 있다.

   ```javascript
   new Array(-1); // RangeError: Invalid array length

   console.log(foo); // ReferenceError: foo is not defined

   fetch('https://nonexistent-domain.nowhere'); // TypeError: Failed to fetch
   ```

2. 코드 실행 중에 에러가 발생하면, **코드의 실행이 중단되어 그 시점에 실행 중이었던 작업을 완료할 수 없게 된다.** JavaScript는 이로부터 **코드의 실행 흐름을 원상복구**할 수 있는 기능을 제공하며, `try...catch...finally` 구문을 사용하면 에러가 나더라도 코드의 실행을 지속할 수 있다.

   ```javascript
   try {
     console.log('에러가 나기 직전까지의 코드는 잘 실행됩니다.');
     new Array(-1); // RangeError: Invalid array length
     console.log('에러가 난 이후의 코드는 실행되지 않습니다.');
   } catch (e) {
     console.log('코드의 실행 흐름이 catch 블록으로 옮겨집니다.');
     alert(`다음과 같은 에러가 발생했습니다: ${e.name}: ${e.message}`);
   }
   ```

3. 에러가 났을 때 원상복구를 시도할 코드를 `try` 블록 내부에 작성하면, 에러가 발생했을 때 코드의 실행 흐름이 `try`블록에서 `catch` 블록으로 옮겨간다. 이 때, `catch` 블록 안에서는 에러에 대한 정보를 담고 있는 객체(위 코드의 `e`)를 사용할 수 있다.

4. `try` 블록이 예외 처리를 위해서만 쓰이는 것은 아니다. `try` 블록 바로 뒤에 `finally` 블록이 오면, `finally`블록에 있는 코드는 `try` 블록 안에서의 에러 발생 여부와 관계 없이 **무조건 실행된다.** 심지어 `try` 블록 내에서 `return`, `break`, `continue` 등으로 인해 **코드의 실행 흐름이 즉시 이동될 때에도 마찬가지**다.

   ```javascript
   for (let i of [1, 2, 3, 4, 5]) {
     try {
       if (i === 3) {
         break;
       }
     } finally {
       console.log(`현재 i의 값: ${i}`);
     }
   }
   ```

5. 왠지 에러가 발생할 것 같은 코드를 `try` 블록 안에 작성한다. `try` 블록 안에서 에러가 발생하면 `try` 블록 내부의 나머지 코드는 실행이 되지 않고 코드의 실행 흐름이 `catch` 블록으로 옮겨간다.

6. `finally` 블록은 `catch` 블록과도 같이 사용된다. 이 때 코드의 실행 순서를 정리해 보면 다음과 같다.

   1. 에러가 안 났을 때: `try` - `finally`
   2. 에러가 났을 때: `try` - **에러 발생** - `catch` - `finally`

<br />

### 1.2 직접 에러 발생시키기

1. `Error` 생성자와 `throw` 구문을 사용해서 프로그래머가 직접 에러를 발생시킬 수 있다.

   ```javascript
   const even = parseInt(prompt('짝수를 입력하세요'));
   if (even % 2 !== 0) {
     throw new Error('짝수가 아닙니다.');
   }
   ```

2. 간혹 프로그램을 작성하면서 **에러의 종류를 구분**해야 하거나 **에러 객체에 기능을 추가**해야 할 필요가 있다. 이런 경우에는 **Error를 상속받는 클래스**를 만들어서, `throw` 구문에서 이 클래스를 대신 사용할 수 있다. 예를 들어, 아래 `MyError` 클래스를 통해 에러 객체를 생성할 때 에러에 대한 상세 정보를 포함시키면, `catch` 블록 안에서 원상 복구를 위해 이 값을 활용할 수 있다.

   ```javascript
   class MyError extends Error {
     constructor(value, ...params) {
       super(...params);
       this.value = value;
       this.name = 'MyError';
     }
   }

   try {
     const even = parseInt(prompt('짝수를 입력하세요'));
     if (even % 2 !== 0) {
       throw new MyError(even, '짝수가 아닙니다.');
     }
   } catch (e) {
     if (e instanceof MyError) {
       console.log(e.value);
     }
   }
   ```

3. 사용자 정의 에러 또한 `name`과 `message` 속성을 갖고 있다.

4. 실제로 서비스를 만들 때는 에러를 직접 만들일이 많이 없겠지만, 라이브러리를 만들 때 사용자가 해당 라이브러리를 잘못사용했을 때 에러를 발생시키기 위한 용도 정도로 사용된다.

5. Error 객체에 메소드를 추가하거나(기능을 확장), 정확히 어떤 값을 입력해서 에러가 발생한 것인지 알고 싶다면 Error 객체를 확장하여 사용하도록 한다.

<br />

### 1.3 비동기식 코드에서의 예외 처리

#### 1.3.1 비동기 콜백

1. **비동기식으로 작동하는 콜백**의 **내부**에서 발생한 에러는, **콜백 바깥**에 있는 `try` 블록으로는 잡아낼 수 없다.

   ```javascript
   try {
     setTimeout(() => {
       throw new Error('에러!');
     });
   } catch (e) {
     console.error(e);
   }
   ```

2. JavaScript 엔진은 에러가 발생하는 순간 **호출 스택을 되감는 과정**을 거친다. **이 과정 중에 try 블록을 만나야** 코드의 실행 흐름을 원상복구시킬 수 있다. 위 예제에서 `setTimeout`에 넘겨진 콜백에서 에러가 발생하면, 호출 스택을 따라 올라가도 `try` 블록을 만나는 것이 아니므로, 코드의 실행 흐름이 `catch` 블록으로 옮겨지지 않는 것이다. 따라서, 위 예제의 `try` 블록을 비동기 콜백 내부에 작성해주어야 한다.

   ```javascript
   setTimeout(() => {
     try {
       throw new Error('에러!');
     } catch (e) {
       console.error(e);
     }
   });
   ```

<br />

> `console.error()`를 이용하여 에러f를 출력할 수 있다.

<br />

#### 1.3.2 Promise

1. Promise 객체는 세 가지 상태를 가질 수 있다.

   1. pending - Promise 객체에 결과값이 채워지지 않은 상태
   2. fulfilled - Promise 객체에 결과값이 채워진 상태
   3. **rejected - Promise 객체에 결과값을 채우려고 시도하다가 에러가 난 상태**

2. Promise 객체가 rejected 상태가 되면, 이 Promise에 대해서는 `then` 메소드에 첫 번째 인자로 넘겨준 콜백이 실행되지 않고, **두 번째 인자로 넘겨준 콜백**이 대신 실행된다. 그리고 이 콜백에는 **에러 객체가 첫 번째 인자**로 주어진다.

   ```javascript
   const p = new Promise(resolve => {
     const even = parseInt(prompt('짝수를 입력하세요'));
     if (even % 2 !== 0) {
       throw new Error('짝수가 아닙니다.');
     } else {
       resolve(even);
     }
   });

   p.then(even => {
     return '짝수입니다.';
   }, e => {
     return e.message;
   }).then(alert);


   ```

3. 혹은, **catch 메소드**를 통해 에러 처리 콜백을 지정해줄 수도 있다.

   ```javascript
   p.then(even => {
     return '짝수입니다.';
   }).catch(e => {
     return e.message;
   }).then(alert);
   ```

4. 만약, `then` 메소드의 연쇄 안에서 에러가 발생하면, `try...catch` 구문과 유사하게 **처음 만나는 에러 처리 콜백으로 코드의 실행 흐름이 건너뛰는 결과**를 낳게 된다.

   ```javascript
   Promise.resolve()
     .then(() => {
       throw new Error('catch 메소드를 통해 예외 처리를 할 수 있습니다.');
     })
     .then(() => {
       console.log('이 코드는 실행되지 않습니다.');
     })
     .catch(e => {
       return e.message;
     })
     .then(console.log);
   ```

5.  `throw` 키워드를 사용하면 에러가 발생했을 때 후속 코드를 실행시키지 않으므로 Promise 객체의 콜백 함수 안에서 `reject`를 사용하기보다 `throw`를 사용하는 것이 좋다.

6. Promise 객체안에서 `resolve`와 `reject`를 동시에 호출하면 무조건 먼저 호출된 값으로 채워지게 된다. 한 번 `fulfilled`되었거나 `rejected`된 Promise는 그 이후부터 상태가 변경되지 않는다.

#### <br />

### 1.3.3 비동기 함수

1. 앞에서 봤던 Promise 객체의 예외 처리 방식은, 일반적인 동기식 예외 처리 방식과 다르게 **콜백**을 사용하고 있어서 코드를 복잡하게 만드는 원인이 된다.

2. 비동기 함수 내부에서는, **rejected 상태가 된 Promise 객체**를 동기식 예외 처리 방식과 동일하게 **try...catch...finally 구문으로 처리할 수 있다.**

3. Rejected 상태의 Promise를 await하게 되면 에러가 발생한다.

   ```javascript
   async function func() {
     try {
       const res = await fetch('https://nonexistent-domain.nowhere');
     } catch (e) {
       console.log(e.message);
     }
   }

   func(); // 출력 결과: Failed to fetch
   ```

4. 단, Promise 객체에 대해 **await 구문**을 사용하지 않는 경우, 에러가 발생해도 `catch` 블록으로 코드의 실행 흐름이 이동하지 않는다는 사실을 기억하자.

   ```javascript
   async function func() {
     try {
       fetch('https://nonexistent-domain.nowhere');
     } catch (e) {
       console.log(e.message);
     }
   }

   func(); // 아무것도 출력되지 않습니다.
   ```

<br />

<br />

## 2. REST API

1. [RESTful API Designing guidelines — The best practices](https://wayhome25.github.io/etc/2017/11/26/restful-api-designing-guidelines/)

<br />

### 2.2 fetch API

1. [fetch API](http://hacks.mozilla.or.kr/2015/05/this-api-is-so-fetching/)

2. fetch API의 두 번째 인자로 객체 안에 요청 메소드를 지정하여 전달할 수 있다. 소문자를 써도 잘 인식하지만, 대문자가 표준이므로 꼭 대문자로 작성하도록 한다. `json-server`와 같이 특정 라이브러리들이 소문자 메소드를 인식하지 못하는 경우가 있기 때문이다.

   ```javascript
   // DELETE 요청
   await fetch('http://localhost:3000/comments/1', {method: 'DELETE'})

   const res = await fetch('http://localhost:3000/comments')
   const data = await res.json()
   ```

   ```javascript
   // POST 요청
   const res = await fetch('http://localhost:3000/comments', {
   	method: 'POST',
   	body: JSON.stringify({body: '댓글 내용', postId: 1}),
   	headers: {
   		'Content-Type': 'application/json'
       }
   })

   const data = await res.json() // {body: "댓글 내용", postId: 1, id: 1}
   ```

<br />

### 2.2 MIME Type

1. 파일이 어떤 형태인지 정해놓은 표준을 MIME Type이라고 한다.
2. [MDN - MIME Type](https://developer.mozilla.org/ko/docs/Web/HTTP/Basics_of_HTTP/MIME_types)
3. 서버에 json 파일을 보낼 때 Content-Type 헤더에 `application/json`을 포함시켜주는 것이 표준적인 사용 방식이다.
4. Postman을 사용하면 Content-Type과 같은 정보를 직접 작성하지 않더라도 알아서 처리해준다.

<br />

> 복사해서 사용할 수 있는 파일을 만들 때에는 파일명 뒤에 .dist로 붙여 써주는게 관례이다(distribution의 약자).

<br />

<br />

## 3. 기타 

1. node_modules는 용량이 크기 때문에 github에 그대로 올리지 않는다. .gitignore에 추가하는 것이 필수적이다.

2. package.json 파일에서 name, version, descriptor는 npmjs.com에 업로드했을 때 필요한 정보이므로, 그럴 예정이 아니라면 사실은 건들 필요가 없다.

3. `rm -rf` 명령에서 `r` 옵션은 폴더가 중첩되어 있을 때 그 하위에 있는 모든 내용까지 다 지우겠다는 뜻이고 f 옵션은 물어보지 않고 강제로 지우겠다는 뜻을 나타낸다.

4. package-lock.json: package.json만 가지고는 정확히 어떤 버전을 설치할 지 알 수 없다. package-lock.json이 정확한 버전에 대한 정보를 제공한다. 프로젝트를 github에 업로드할 때 같이 올려줘야 한다.

5. [package.json과 package-lock.json의 혼재](https://medium.com/@pyeonjy97/package-json%EA%B3%BC-package-lock-json%EC%9D%98-%ED%98%BC%EC%9E%AC-83b80518c453)

6. 토큰과 같이 개인적인 것들은 .gitignore 파일에 추가하여 원격 저장소에 업로드되지 않도록 해야 한다.

7. [gitignore.io](https://www.gitignore.io/) 사이트를 이용하여 .gitignore 파일을 쉽게 생성할 수 있다.

8. 전역으로 설치한 json-server는 환경변수 설정이 되어있지만, 지역으로 설치한 json-server는 node_modules 폴더 안에 존재하는데 환경변수 설정이 안 되어있는 문제를 해결하기 위해 npx 명령을 붙여서 json-server를 실행한다.

   ```bash
   npx json-server --watch db.json
   ```

9.  vscode에서 CMD + SHIFT + P를  누른 후에 >workspace setting를 입력하여 이동하면 모든 프로젝트에 적용될 설정, 각 프로젝트 별로 적용될 설정을 지정할수 있다. 위 명령을 실행하면 seetings.json이 생성되는데, `liveServer.settings.ignoreFiles`을 우측 영역에 복사한 후 db.json을 추가하면 db.json이 변경되더라도 라이브 서버에서 새로 고침이 일어나지 않는다.